version: "3.1"

services:
  web:
    build: .
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
       - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

